modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/kreezxil/Terracart-Reloaded/issues"
license="MIT"

[[mods]]
modId="terracart"
version="${file.jarVersion}"
displayName="TerraCart Reloaded"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/terracart-reloaded"
#logoFile="examplemod.png"
credits="Thanks to Lime for maintaining this from 1.7.10 thru 1.11.2. After a few months of no activity and no response I put the WTFPL license to use and recompiled it with some 1.12.2 porting changes."
authors="Kreezxil, Lime"
description='''
Boomshakalaka!!! Right click any track and enjoy!
'''